### ISSUE TITLE
Core warnings appear if you rm elm-stuff/ and rebuild

### ISSUE THREAD

**Issue by rtfeldman** [dnalot/elm-sublime#4]
To reproduce:

1. `rm -rf elm-stuff/` in your project's root
2. Build from Sublime

Here's what I got:

![screen shot 2015-08-06 at 11 58 00 pm](https://cloud.githubusercontent.com/assets/1094080/9130385/234b50ae-3c97-11e5-853e-a8d09d377def.png)

**Comment by dnalot** [comment]
Yeah I noticed that too but assumed it's upstream. I'll test from the command line tomorrow.

**Comment by dnalot** [comment]
Which file did you have open when you build? So far I've gotten the same output from the command line as the plugin before and after `elm-stuff` creation.

**Comment by dnalot** [comment]
This appears to be the way `elm-make` works. It issues warnings on successful build. Could this be upstream? I confirmed the [warning is correct](https://github.com/elm-lang/core/blob/2a8dcb522f71541c299a8a465bb39bc17bb9ec67/src/Graphics/Collage.elm#L151). Closing for now.
